#
#
# Copyright 2016 The Symphony Software Foundation
#
# Licensed to The Symphony Software Foundation (SSF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

language: java

before_install:
  - "curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.30.2/install.sh | bash"
  - "nvm install 6.10"
  - "nvm use 6.10"
  - "npm update -g npm"

install: true

jdk:
  - oraclejdk8

env:
  global:
    - secure: "sBlTcgueSir9yRcuBivjrpIp7SYwEuqwePwnKyZADNqnvDpDKUrLzvyyjUrx+Mq8yBApi5qc5/Y7rtm4goTpP8QoVDjIW+ESyLPWrvbxacGGU7SVQwqoDLdd608F022iilBuO4hclHS7SL7ReklB2YKc77GDcBLk5U+lQr55S+0qFuqBBc2gZTpjHc/DzQGqTHHOzs3i2onfi/M75PsAN80ajm6FzSpbyMYKu82IpIOBKiPSeUcEf4OUIQPyuFTf6VJS5K/ZzyV08ajM6XcIwq3yVHD/9lEW7AbCYKRdrSyBC1PeXC8xvsIp1KPtYJbqV6dmkvaZpX2a8wSke8suF0xZCf5FfXzTwIT0V0Bxel7bpBR3POwq79E8MM0tSCzhhVSWGA+igv0TQnDPlPmcj37t89IwVr6Vu360/9QPCCGfJjr3N6/aIS7Ldz3CGlEofr/R2LVg5awl2W/JZgaKrW9hCjlFB+gDE0GkbCuAA4Ws2zlgZRBTOPg3/QMglaLNySPnjrsQWR8RT3X8P/2LEbRmqIdC+UhBBpNY0SnNl6NnSX10oWjcWdOLSxrw+5sBzhhAz8Ejud6mkCO666ZiwzmsoOoL0lQDDfZw3d0vNhSVvyJ41ytDhXbfDEW4/ACZ+wcYNfURwXnsobAaKOQoQS5OFxwZTbfKNbsB+jMW4tk="

addons:
  coverity_scan:
    project:
      name: "symphonyoss/App-Integrations-Universal"
      description: "Build submitted via Travis CI"
    notification_email: "integrations-team@symphony.com"
    build_command_prepend: "mvn clean"
    build_command:   "mvn -Denv=dev -DsymphonySkipUnitTests=true install"
    branch_pattern: "dev"

script:
- "if [[ \"$TRAVIS_PULL_REQUEST\" = \"false\" && $TRAVIS_BRANCH =~ dev ]]; then mvn clean deploy -Pversioneye -Pcobertura -DtransitiveDependencies=true --settings settings.xml ; fi"
- "if [[ \"$TRAVIS_PULL_REQUEST\" != \"false\" ]]; then mvn clean package -Pcobertura; fi"

after_success:
- bash <(curl -s https://codecov.io/bash)